name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  lint:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Self test
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm ci
      - run: npm run lint
      - run: npm run posttest
